parameters:
- name: image_type
  displayName: Build Agent Image
  type: string
  default: windows2019
  values:
  - windows2019
  - windows2022
  - ubuntu2004
  - ubuntu2204
- name: variable_group
  displayName: Variable Group
  type: string
  default: Selfhostedagents
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: EUS-VMSET-KMP-DEV-ADO-SET-02

trigger: none

variables:
  - group: ${{ parameters.variable_group }}

jobs:
- template: buildagent-generation-template.yml
  parameters: 
    image_type: ${{ parameters.image_type }}
    variable_group: ${{ parameters.variable_group }}
    agent_pool: ${{ parameters.agent_pool }}
